# Generated by Django 5.2 on 2026-01-07 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("CREDIT", "Credit"), ("DEBIT", "Debit")],
                        max_length=10,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("category", models.CharField(default="General", max_length=50)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("sender", models.CharField(blank=True, max_length=100, null=True)),
                ("receiver", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="wallet.wallet",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Savings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("goal_name", models.CharField(max_length=100)),
                ("target_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "current_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("icon", models.CharField(blank=True, max_length=50)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="savings",
                        to="wallet.wallet",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_name", models.CharField(max_length=50)),
                ("card_number", models.CharField(max_length=16)),
                ("card_holder", models.CharField(max_length=100)),
                ("expiry_date", models.CharField(max_length=5)),
                ("cvv", models.CharField(max_length=3)),
                (
                    "card_type",
                    models.CharField(
                        choices=[("VISA", "Visa"), ("MASTERCARD", "Mastercard")],
                        default="MASTERCARD",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="wallet.wallet",
                    ),
                ),
            ],
        ),
    ]
